workflows:
  android:
    name: GibelaSA Android

    environment:
      flutter: stable

    scripts:
      - name: Get dependencies
        script: |
          cd mobile
          flutter pub get

      - name: Build Android
        script: |
          cd mobile
          flutter build apk --release

    artifacts:
      - mobile/build/app/outputs/flutter-apk/*.apk

  ios:
      name: GibelaSA iOS IPA

      environment:
        flutter: stable
        xcode: latest
        cocoapods: default

      scripts:
        - name: Get dependencies
          script: |
            cd mobile
            flutter pub get

        - name: Build iOS without signing
          script: |
            cd mobile
            flutter build ios --release --no-codesign

        - name: Create IPA for Sideloadly
          script: |
            cd mobile

            rm -rf Payload
            mkdir Payload

            cp -R build/ios/iphoneos/Runner.app Payload/

            zip -r GibelaSA.ipa Payload

            rm -rf Payload

      artifacts:
        - mobile/GibelaSA.ipa
        - mobile/build/ios/iphoneos/Runner.app